### ISSUE TITLE
Remove Empty Users' Objects in 2021 and 2022 Data 

### ISSUE THREAD

**Issue by bilalix** [geeksblabla/stateofdev.ma#100]
There are 253 users with empty entries in the `results.js` of the 2021 survey, see [2021 notebook](https://github.com/bilalix/stateofdev.ma/blob/add_2021_2022_csv/results/2021/data/csv/2021_data_processing.ipynb) (`Remove Empty users` section at the bottom).

They can be removed from `results.js`.

> Same thing for 2022 data with 367 empty submitters

**Comment by yjose** [comment]
Hmm, what  you to check if those empty entries are included in the total number of responses or not. 


After deleting those empty entries we should have  : 

2020 => 2287 entries 
2021 => 1098  entries 
2022 => 1617  entries 

if its the case we can remover them from the results data, if its not the case we need to check if there is something wrong here 

thanks @bilalix

**Comment by bilalix** [comment]
> 2020 => 2287 entries
> 2021 => 1098 entries
> 2022 => 1617 entries

@yjose  may I ask where did you get those numbers from?

As for:
* 2021 => 1098 entries: Yes, that's the exact number I got after removing empty users (please see the [last output here](https://github.com/bilalix/stateofdev.ma/blob/add_2021_2022_csv/results/2021/data/csv/2021_data_processing.ipynb))
* 2022 => 1617 entries: [Same thing for 2022].(https://github.com/bilalix/stateofdev.ma/blob/add_2021_2022_csv/results/2022/data/csv/2022_data_processing.ipynb)

I didn't check the 2020 data though, I'll do that.

**Comment by yjose** [comment]
@bilalix  easy, just check the hero section for every year in the website 😀 https://stateofdev.ma/
or simple check the first question in the report and we will see the total resps. 

I think the data is correct, you can remove empty entries

**Comment by bilalix** [comment]
> @bilalix easy, just check the hero section for every year in the website 😀 https://stateofdev.ma/ or simple check the first question in the report and we will see the total resps.
> 
> I think the data is correct, you can remove empty entries

Lol, Thanks, I missed that one 🤦
I'll check 2020 data, make sure it makes sense and make the required changes

**Comment by yjose** [comment]
I can understand why we have some empty entries, as we are using firebase to collect data with anonymous user. some user will only authenticate without taking the first part of the survey, which means we create a new entry with no responses

**Comment by bilalix** [comment]
> I can understand why we have some empty entries, as we are using firebase to collect data with anonymous user. some user will only authenticate without taking the first part of the survey, which means we create a new entry with no responses

That makes sense, in this case, shall delete them or it's okay to leave them there as long as they aren't affecting the stats?

**Comment by yjose** [comment]
yeah you can delete theme and prepare a new PR

**Comment by bilalix** [comment]
@yjose, the PR #103 is ready.
