### ISSUE TITLE
Fix all contributors bot

### ISSUE THREAD

**Issue by bilalix** [geeksblabla/stateofdev.ma#101]
allcontributors bot throws this error
```
This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token { in JSON at position 4169
```

When trying to add a new contributor (see: https://github.com/geeksblabla/stateofdev.ma/pull/97#issuecomment-1445433425) 

It may be fixable by simply [deleting and reinstalling the bot](https://github.com/Atri-Labs/atrilabs-engine/issues/372#issuecomment-1282926299), this needs maintainer privileges I assume.

**Comment by yjose** [comment]
@all-contributors please add @bilalix for content

**Comment by yjose** [comment]
@all-contributors please add @bilalix for code

**Comment by yjose** [comment]
Fixed, thank you @bilalix. a local running for all-contributors cli was needed to fix the issue + reinstall the bot as you mentioned
