### ISSUE TITLE
Missing a 'Skip' Option for q-5 in part 4

### ISSUE THREAD

**Issue by elqessouartariq** [geeksblabla/stateofdev.ma#113]
![image](https://github.com/geeksblabla/stateofdev.ma/assets/73233952/80baa569-a7ea-4251-99d5-8ab126231dea)

## Issue Identified
This Question may not be relevant to everyone (e.g., students or non-AI-related workers).

## Problem Highlighted
Lack of suitable choices may lead to random or forced answers, impacting data accuracy.

## Suggestion
- Introduce a "Skip" button for questions unrelated to certain respondent groups.
- Enable easy skipping of questions not applicable to the respondent's situation.

**Comment by yjose** [comment]
Yeah i think you are right, we should make it optional

**Comment by yjose** [comment]
Fixed
