### ISSUE TITLE
enable multiple choices for question: 10. What do you usually drink while coding?

### ISSUE THREAD

**Issue by ans1genie** [geeksblabla/stateofdev.ma#65]
would make sense to have multiple choices for `question: 10. What do you usually drink while coding?`
2 or 3 maybe?

![image](https://user-images.githubusercontent.com/16513804/140501686-52824724-3985-4e9d-b8cd-c66fd476b82d.png)

**Comment by yjose** [comment]
Maybe we can add this option next year, right now we cant update the survey condition as we already collect data

**Comment by ans1genie** [comment]
thanks 😄  @yjose

**Comment by aboullaite** [comment]
This was fixed AFAIK. Closing it now
