### ISSUE TITLE
Where is linkedin?

### ISSUE THREAD

**Issue by midrissi** [geeksblabla/stateofdev.ma#85]
![image](https://user-images.githubusercontent.com/3237344/208551291-a1b67281-d1f9-4fa9-a38c-0a01b09279fc.png)

**Comment by yjose** [comment]
@midrissi  hhhh interesting, for some reasons we messed it 😀 will add it next time. we cant add new option on the fly unfortunately

**Comment by aboullaite** [comment]
I believe it is now fixed! Going to close this foe now. Feel free to reopen if you don't agree
